sudo: false
language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.7.1
  - 3.0.0

jobs:
  include:
  - rvm: 2.0
    before_install: gem install bundler -v 1.17.3
  - rvm: 2.1
    before_install: gem install bundler -v 1.17.3
  - rvm: 2.2
    before_install: gem install bundler -v 1.17.3
  - rvm: 2.3
    before_install: gem install bundler
  - rvm: 2.4
    before_install: gem install bundler
  - rvm: 2.6
    before_install: gem install bundler
  - rvm: 2.7
    before_install: gem install bundler
  - rvm: 3.0  
    before_install: gem install bundler
    dist: focal # Workaround for: https://github.com/rvm/rvm/issues/5133
  
script: bundle exec rake spec
